* issues with gpu amd

link: https://davejansen.com/quick-how-to-fix-screen-tearing-in-ubuntu-with-amd-gpus/

main fix:
Let's fix screen tearing
Open up a terminal window and cd to /etc/X11. You'll either need to sudo each of the following commands, or start a sudo session using sudo -s as the files and folders we'll be working with are owned by root.

We'll need to create a new sub-folder here if one doesn't already exist called xorg.conf.d, so do that now if there indeed is no such folder yet. Then, cd into it and, using your favorite text editor, create a new file called 20-amdgpu.conf with the following contents:

Section "Device"
        Identifier      "AMD Graphics"
        Driver          "amdgpu"
        Option          "TearFree" "true"
EndSection

If you already have a configuration file here for amdgpu, the important bit here is setting TearFree, so you can add that to your existing file.

This should be all there is to it. Just reboot (or relaunch X I suppose) and you should now be able to enjoy a tear-free experience. Why this (still) isn't the default, I don't know, but here we are.
