* sudo
-E flag preserves Environment args! So `sudo -E bla bla` will use $http_proxy etc for example.

** run command as sudo without password:
register the command in /etc/sudoers

#+begin_src emacs-lisp
(find-file "/sudo:root@localhost:/etc/sudoers")
#+end_src

edit /etc/sudoers
danielhabib ALL=(ALL) NOPASSWD: /home/danielhabib/bin/mobile.sh

* rm
removing with the -f (force) flag does not raises an error if a file does not exist!

* logrotate

https://www.redhat.com/en/blog/setting-logrotate

configuration file /etc/logrotate.conf

The directives `weekly`, `dateext`, `compress`, `create`, and `rotate 4` state that log files are to be rotated weekly, that the date of rotation be used as the identifying suffix of the rotated files, that the rotated files should be compressed, that a new file is to be created to receive incoming logs, and that no more than four logs should be kept.

There is a directive to include a particular folder: `/etc/logrotate.d`

crontab is already "always" configured with a call to logrotate every day at /etc/cron.daily/logrotate

* update-alternatives

** register a custom alternative

sudo update-alternatives --install /usr/bin/java java /home/danielhabib/dev/jdk/jdk-21.0.2/bin/java <priority>

** select one to use

sudo update-alternatives --config java
